name: Amplify Loop

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-loop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install @aws-sdk/client-amplify @aws-sdk/client-wafv2 simple-git

      - name: Setup Git identity
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "github-actions-bot"

      - name: Run loop
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AMPLIFY_GITHUB_TOKEN: ${{ secrets.AMPLIFY_GITHUB_TOKEN }}
        run: |
          while true
          do
            node scripts/automate.js
            sleep 600
          done
